### ISSUE TITLE
Filtering does not work on Windows

### ISSUE THREAD

**Issue by mrkaban** [TechnikEmpire/StahpIt-WPF#7]
Hello, very interesting and promising project! I wanted to add free software for Windows to my catalog, but I never managed to get the program to work.

I tried on Windows 10 and Windows 7, different versions of the bit. The program starts, replenishes the list of filtered applications, all tick. I try to access all sites, even English ones, and open all advertising banners, but still 0 bytes are filtered out.

**Comment by TechnikEmpire** [comment]
@mrkaban This engine and program is ancient. I've rewritten the filtering engine in C# and created an independent URL filtering library based on adblock plus filters:

https://github.com/TechnikEmpire/CitadelCore.Windows

https://github.com/TechnikEmpire/DistillNET

If I had time, I'd blow away HttpFilteringEngine out of this project, replace it with CitadelCore.Windows and replace URL filtering with DistillNET. It's trivial to do.
